### ISSUE TITLE
Summary comments

### ISSUE THREAD

**Issue by eko24ive** [Serhii7/homework5#3]
1) Why you declare two styles for `p` element:
```css
.text_content p{
	font-size: 20px;
	line-height: 1.45;
}
.text_content p:first-child{
	font-size: 50px;
	padding-top: 120px;
}
```
They are summed up in the end:
![image](https://cloud.githubusercontent.com/assets/25591824/22869410/82fde3e2-f1a7-11e6-8835-db30e533665e.png)

It's better to move styles from `.text_content p:first-child` to `.text_content p`

2) You are using `.item_content:nth-child(3n+3)` to remove top border, you could achive it with more short and verbose construction using `:last-child` pseudoclass
